POST https://phonebook-api-kxh4.onrender.com/api/persons
Content-Type: application/json

{
    "name": "Sandro Bortolotti",
    "number": "684204289"
}

###
GET https://phonebook-api-kxh4.onrender.com/api/persons